version: "3"

networks:
  net0:

services:
  webserver:
    image: monoann/film
    container_name: '7.4.x-webserver'
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 7000:80
      - 8000:443
    depends_on: 
      - mysql
    volumes: 
      - /data/diplom/films/www:/var/www/html
      - /data/diplom/films/config/php/php.ini:/usr/local/etc/php/php.ini
      - /data/diplom/films/config/vhosts:/etc/apache2/sites-enabled
      - /data/diplom/films/logs/apache2:/var/log/apache2
    networks:
      net0:
  mysql:
    image: monoann/db
    container_name: 'mysql'
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - /data/diplom/films/data/mysql/:/var/lib/mysql/
      - /data/diplom/films/logs/mysql/:/var/log/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      net0:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'sc-phpmyadmin'
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${USER_MYSQL}
      PMA_PASSWORD: ${USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${USER_MYSQL}
      MYSQL_PASSWORD: ${USER_PASSWORD}
    ports:
      - '8181:80'
    volumes: 
      - /sessions
    networks:
      net0:
  redis:
    container_name: 'sc-redis'
    image: redis:latest
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - mysql
    ports:
      - "${HOST_MACHINE_REDIS_PORT}:6379"
    networks:
      net0:
  adminer:
    image: adminer
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - mysql
    networks:
      net0:
